### ISSUE TITLE
Cannot save the settings

### ISSUE THREAD

**Issue by vyskoczilova** [vyskoczilova/woocommerce-payforpayment#10]
after saving i do now get not a blank page, but it does not save the changes. 

i have set debug to on. but i do not see a debug file in wp-conent, 
plus i now have also set display on sceen to true. no error. 

any idea? 

Post Link: https://wordpress.org/support/topic/cannot-save-the-setting-page-any-more-any-ideas/#post-9133687

**Comment by vyskoczilova** [comment]
Can't reproduce, @oblaum, let me know, if you can provide more info.

**Comment by oblaum** [comment]
with 2.01 it works. great work karlolina!!!! thank you very very much!!! :) oli

**Comment by vyskoczilova** [comment]
You're welcome :)

**Comment by DirkjanDikkenberg** [comment]
[Tue Sep 12 10:54:29.165093 2017] [proxy_fcgi:error] [pid 20609:tid 139972132607744] [client 31.161.69.122:50362] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Unsupported operand types in /home/glasweb/domains/glaswebwinkel.nl/public_html/wp-content/plugins/woocommerce-pay-for-payment/inc/class-pay4pay-admin.php:259\nStack trace:\n#0 /home/glasweb/domains/glaswebwinkel.nl/public_html/wp-includes/class-wp-hook.php(298): Pay4Pay_Admin->update_payment_options('')\n#1 /home/glasweb/domains/glaswebwinkel.nl/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(false, Array)\n#2 /home/glasweb/domains/glaswebwinkel.nl/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)\n#3 /home/glasweb/domains/glaswebwinkel.nl/public_html/wp-content/plugins/woocommerce/includes/admin/settings/class-wc-settings-checkout.php(370): do_action('woocommerce_upd...')\n#4 /home/glasweb/domains/glaswebwinkel.nl/public_html/wp-includes/class-wp-hook.php(298): WC_Settings_Payment_Gateways->save('')\n#5 /home/glasweb/domains/glaswebwinkel.nl/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)\n#6...\n',

I have this error, what do i do? I think i have the same issue as oblaum.


I
