### ISSUE TITLE
$fragment_refresh is not defined

### ISSUE THREAD

**Issue by vasikgreif** [vyskoczilova/woocommerce-payforpayment#13]
I'm  getting following error on WC 2.6.14:

`$fragment_refresh is not defined`

Any idea how to fix that one?

**Comment by diggy** [comment]
Included following fix in a (private) fork of the original repo a while ago:

````
if(typeof $fragment_refresh !== 'undefined') {
    $.ajax($fragment_refresh);
}
````

**Comment by vyskoczilova** [comment]
Thanks @diggy, I will merge it to the plugin.
