### ISSUE TITLE
Fee row does not disappear when I change shipping method

### ISSUE THREAD

**Issue by tomascarlo** [vyskoczilova/woocommerce-payforpayment#15]
Suppose I have
- 2 shipping methods, shippingA and shippingB
- 2 payment gateways, cash-on-delivery and paypal.
Suppose that cash-on-delivery is enabled only for shippingA, with 5€ fee.
If I click on shippingA in the checkout page and then select "cash on delivery" as payment gateway, the "fee" row correctly appears.
Now if I select shippingB (**with no changes in gateway selection!**), the fee row remains still visible, despite the shippingB method does not "support" cod.
I use WP 4.7.5 and WC 3.0.3.

thank you in advance
Carlo

**Comment by vyskoczilova** [comment]
Hi @tomascarlo, sorry, I was at vacations.
Could you try on WP Twenty seventeen theme? It could be an theme issue, because I'm not able to replicate this myself. And ideally, update to the latest WP and WC.
Thanks and cheers
Karolina
