### ISSUE TITLE
Coupons supported?

### ISSUE THREAD

**Issue by michaelrimbach** [vyskoczilova/woocommerce-payforpayment#18]
Hi,

what means "Coupons are not supported. (Sorry guys. I tried, but no way.)". 
I found it in the github readme, but not in the WP repo plugin description.

Michael

**Comment by vyskoczilova** [comment]
That means, that it's not currently possible to create a coupon which will affect the payment fee.  Otherwise, they work as they could. That was stated with the previous author and I haven't changed it in this case. If you want to work on it, you're welcomed to fork.

**Comment by michaelrimbach** [comment]
Thanks!
