### ISSUE TITLE
Fatal error Unsupported operand types line 264

### ISSUE THREAD

**Issue by vyskoczilova** [vyskoczilova/woocommerce-payforpayment#20]
Compatibility with: plugin for the e-boekhouden.nl plugin, it sync’s orders to there system.
https://wordpress.org/support/topic/fatal-error-2621/

**Comment by vyskoczilova** [comment]
https://wordpress.org/support/topic/unsupported-operand-types-2/

**Comment by Musilda** [comment]
Chyba znamená, že když $extra je pole, tak $option pole není. Bylo by třeba zjistit, jak to ten plugin ukládá, nebo zda to není prázdné. To option může být i serialize, tak zkusit použít maybe_unserialize() funkci.

**Comment by vyskoczilova** [comment]
@Musilda Díky za tip. To se mi právě nepovedlo, u těc Sisow payments mi to funguje a Mollie payments mne nepustí do nastavení bez API key, takže jsem to nemohla otestovat. Zkusím uživatele poprosit, aby mi poslali var_dump($options) a uvidíme, co tam mají.

**Comment by davdebcom** [comment]
Should be fixed with this pull request:
https://github.com/vyskoczilova/woocommerce-payforpayment/pull/33

**Comment by vyskoczilova** [comment]
Fixed with plugin version 2.0.7 which have been just now released in WP repository.
