### ISSUE TITLE
Wrong sum of the cart

### ISSUE THREAD

**Issue by kozomelec** [vyskoczilova/woocommerce-payforpayment#22]
Hey, 

after last update of Woocommerce I found a bug. I have special fee for payment on delivery, in the summary is the price, but the sum of the cart is not correct. What should I do with it? 

Screen in attachment.

Thanks
![screenshot_12](https://user-images.githubusercontent.com/31568677/31582879-76b74e7c-b18f-11e7-8236-75a16cb82fd2.png)

**Comment by xarkitu** [comment]
Hello,

I add many users of the plugin with the same problem.

We are waiting for the author to return for vacation for the last week of October.

Let's hope the problem is solved quickly.

I am trying to find a solution, if I find a solution I will publish it.

Best regards.

**Comment by xarkitu** [comment]
Hello, 

Solution for the problem:

Edit file /plugins/woocommerce-pay-for-payment/woocommerce-payforpayment.php

comment line 50:
 `//add_action( 'woocommerce_calculate_totals' , array($this,'calculate_pay4payment' ) , 99 );`

Add $this->calculate_pay4payment( ); in line 84:
`	function add_pay4payment( $cart ) {
		$this->calculate_pay4payment( );
		if ( ! is_null($this->_fee) ) {
			$cart->add_fee( $this->_fee->fee_title , 
							$this->_fee->cost , 
							$this->_fee->taxable , 
							$this->_fee->tax_class
						);
			
		}
	}`

This found for my.

Best regards.
