### ISSUE TITLE
Problem with WooCommerce Multilingual

### ISSUE THREAD

**Issue by gustl** [vyskoczilova/woocommerce-payforpayment#24]
Hi,
WooCommerce Multilingual calculates the cart multiple times, before and after storing the changed payment method to the session.
After changing the payment method from pay4pay type to non pay4pay type the additional fee is still displayed and added to the calculation.
Possible Fix is to disable caching of _fee and clear it before each call to calculate_pay4payment: 
    $this->_fee = NULL;
and remove 
   $cart->calculate_totals();
to omit recursion. 

gustl

**Comment by vyskoczilova** [comment]
Hi @gustl I will test it in the next couple of days (I have just returned from a vacation) and if it's ok, I will push it in the next release. Thanks a lot!

**Comment by vyskoczilova** [comment]
Hi @gustl could you add it as a testable pull request? And as well a step by step manual how to reproduce the issue? I tried, but I can't reproduce it.  Thanks.
