### ISSUE TITLE
The WC_Cart->discount_total argument is deprecated since version 2.3.

### ISSUE THREAD

**Issue by xarkitu** [vyskoczilova/woocommerce-payforpayment#25]
The WC_Cart->discount_total argument is deprecated since version 2.3. After tax coupons are no longer supported. For more information see: https://woocommerce.wordpress.com/2014/12/upcoming-coupon-changes-in-woocommerce-2-3/

Solution on line 131 class-pay4pay.php

Change 
$calculation_base -= $cart->discount_total + $cart->discount_cart;
for
$calculation_base -= $cart->get_total_discount() + $cart->discount_cart;

Best regards.

**Comment by vyskoczilova** [comment]
@bolint Thanks a lot! I will push it in the next update (coming soon).
