### ISSUE TITLE
Different price for other country

### ISSUE THREAD

**Issue by vyskoczilova** [vyskoczilova/woocommerce-payforpayment#3]
See: https://wordpress.org/support/topic/different-price-for-other-country/

**Comment by diggy** [comment]
Not sure if this is something this plugin should handle? There's the `woocommerce_pay4pay_{$current_gateway->id}_amount` filter hook which allows to modify the fee amount based on country, language, ...

**Comment by vyskoczilova** [comment]
@diggy true, I will keep it as a possible future premium feature, if this is ever to happen ;)
