### ISSUE TITLE
otázka k prekladu

### ISSUE THREAD

**Issue by Jimmi08** [vyskoczilova/woocommerce-payforpayment#34]
Mám otázku k prekladu do češtiny:
Inclusive Taxes  - bez DPH
The payment fee is inclusive of taxes. - Poplatek zahrnuje i DPH.
- to si nejako odporuje.

To prvé by malo byť Vrátane DPH, či? 
Ďakujem

**Comment by vyskoczilova** [comment]
Díky za upozornění, přesouvám překlad na WP.org, už je to tam opravené.
