### ISSUE TITLE
Hi the plugin give to me these error...

### ISSUE THREAD

**Issue by Statuspm** [vyskoczilova/woocommerce-payforpayment#38]
1. Name of the payment method you are trying to save and the URL where it can be downloaded for testing.

	2. Current section ID: wc_cetelem

	3. Anything else might be helpful (recently added/updated plugins, etc.).

**Comment by vyskoczilova** [comment]
Hi, It looks like the payment gateway is not coded the standard WC way. Could you share me the link to the plugin you are trying to use together with WooCommerce Pay for Payment? I will do some tests and include the fix.

The best would be if you could share with me a testing site or a Duplicator package so I could test myself and don't losing time with setup the payment method.

Thanks a lot!
