### ISSUE TITLE
Can't change setting

### ISSUE THREAD

**Issue by Padi142** [vyskoczilova/woocommerce-payforpayment#47]
Hey! Iam using Pay for payments plugin on Wordpress version 5.2.2 and I have a problem. Whenever I try to change any settings in the plugin (including the fee itself) it resets to default (the fee being 0)  after pressing Save changes button. Any ideas how to fix this? Thanks

**Comment by vyskoczilova** [comment]
Hi @Padi142 Fixed with Fix WC 3.7.0 saving error commit and solved in version 2.0.13 ready for download in WP repository. Sorry for taking it too long, I was on holidays.
