### ISSUE TITLE
How to get Gateway Fee from PHP?

### ISSUE THREAD

**Issue by soyniqolas** [vyskoczilova/woocommerce-payforpayment#50]
I'm modifying the price.php template to show prices with gateway fees.

How can I get a gateway fee from PHP?

For example:
`pay4pay_get_fee($gateway_name); `

(Should return the fee or something similar)
Or maybe input the price and gateway and output all formated price.

**Comment by vyskoczilova** [comment]
Hi, you need to use `get_option()` WP function. check the DB for the exact option name (the easies is too look for the name of your fee or the cost and you'll find it) :)
