### ISSUE TITLE
Not adding fee (BUG)

### ISSUE THREAD

**Issue by mrleonz** [vyskoczilova/woocommerce-payforpayment#55]
Dear,

There is a small bug what i found.

In the checkout page I choose the payment method without fee.
then I come to a payment platform. I click back for another payment method. 
then I press a payment method with fee. 
the fee is not calculated
( the payment page is different then normal)

I hope this is possible to solve :)

thanks in advance!

**Comment by vyskoczilova** [comment]
Hi, I'm sorry, this is a known bug of WooCommerce and its limitation is described on the plugin page - it doesn't work on "Pay for order" pages (manually created orders or canceled payments).

See it here: https://github.com/woocommerce/woocommerce/issues/17794
