### ISSUE TITLE
wpml string and version 2.0

### ISSUE THREAD

**Issue by vyskoczilova** [vyskoczilova/woocommerce-payforpayment#9]
With the new version, i cannot find the string translation in WPML for “Online processing fee”, this did work in 1.x

See: https://wordpress.org/support/topic/wpml-string-and-version-2-0/

**Comment by stuffo** [comment]
Is this realted to the fact that I can't translate the fee_title string in Polylangs WPML compatibility?

**Comment by vyskoczilova** [comment]
@stuffo could you let me know, which payment method you can't translate? I will add it into the config file. 

The problem is that the WPML parts are based on the WPML config file, so if there is a payment method not listed in the `wpml-config.xml` it makes a problem. I will contact the WPML support, what to do with this issue.

**Comment by stuffo** [comment]
@vyskoczilova 
I use stripe (https://wordpress.org/plugins/woocommerce-gateway-stripe/) and Paypal. 

Is it possible to make the configured fee_title string translatable instead of using the payment method name? Like setting fee_title to eg. "Payment fee" and than have this string translated.

**Comment by vyskoczilova** [comment]
@stuffo 
I see, I've added hopefully support for Stripe, for Paypal, I would need the settings string (`woocommerce_paypal_settings `are included), could you please download the latest version from this repo and check, if it did work or not?

The problem is, that the setting fee_title is related to the payment method which you use - you can use multiple payment fees for different payment method and name them differently. I have contacted WPML support for solving this kind of issue and I will let you know.

If you would like to contact somebody at Polylangs about this issue and let me know, I would be more than glad to add the solution it in the next release and if anything needed from my side to cooperate.

**Comment by stuffo** [comment]
@vyskoczilova 
Just wanted to confirm that everything works like intended now (even with PL). Thanks for the fast reaction and working fix. Keep it up!

**Comment by vyskoczilova** [comment]
@stuffo  Thanks, that's great! Good luck with your e-shop! However, I would love to know how to solve the issue not manually adding the gateway, we'll see if guys in WPML will show me how to do it properly.
